// app/blog/[slug]/page.tsx
import React from "react";
import { getPostData, getAllPostIds } from "../../../lib/posts";
import { CalendarIcon } from "lucide-react";

interface Params {
  params: {
    slug: string;
  };
}

export async function generateStaticParams() {
  const paths = await getAllPostIds();
  return paths;
}

export default async function BlogPost({ params }: Params) {
  const postData = await getPostData(params.slug);

  return (
    <main className="min-h-screen w-full bg-white bg-dot-hunter/[0.4] pt-20 px-4 sm:px-6 lg:px-8">
      <article className="max-w-4xl mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
        <div className="p-8 sm:p-12">
          <h1 className="text-4xl sm:text-5xl font-bold text-brunswick mb-6">
            {postData.title}
          </h1>
          <div className="flex items-center text-lg text-gray-500 mb-10">
            <CalendarIcon className="mr-2 h-6 w-6" />
            <time dateTime={postData.date}>{postData.date}</time>
          </div>
          <div
            className="prose prose-xl max-w-none prose-headings:text-brunswick prose-a:text-sage hover:prose-a:text-fern"
            dangerouslySetInnerHTML={{ __html: postData.content }}
          />
        </div>
      </article>
    </main>
  );
}

// src/routes/w/[slug]/+page.svelte
<script lang="ts">
	import { formatDate } from '$lib/utils';

	let { data } = $props();
</script>

<svelte:head>
	<title>{data.meta.title}</title>
	<meta property="og:type" content="article" />
	<meta property="og:title" content={data.meta.title} />
</svelte:head>

<article class="mx-auto max-w-3xl px-4 py-8">
	<hgroup class="mb-8">
		<h1 class="text-3xl font-bold text-gray-900 dark:text-gray-100">{data.meta.title}</h1>
		<p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
			Published at {formatDate(data.meta.date)}
		</p>
	</hgroup>

	<div class="mb-8 flex flex-wrap gap-2">
		{#each data.meta.tags as tag}
			<span
				class="rounded-full bg-gray-200 px-3 py-1 text-sm text-gray-800 dark:bg-gray-700 dark:text-gray-200"
			>
				&num;{tag}
			</span>
		{/each}
	</div>

	<div class="prose dark:prose-invert max-w-none">
		<data.content />
	</div>
</article>
